// Code generated by counterfeiter. DO NOT EDIT.
package handlersfakes

import (
	"sync"

	"github.com/ankeesler/btool/node"
	"github.com/ankeesler/btool/node/pipeline/handlers"
	"github.com/ankeesler/btool/node/registry"
)

type FakeDecoder struct {
	DecodeStub        func(*registry.Node) (*node.Node, error)
	decodeMutex       sync.RWMutex
	decodeArgsForCall []struct {
		arg1 *registry.Node
	}
	decodeReturns struct {
		result1 *node.Node
		result2 error
	}
	decodeReturnsOnCall map[int]struct {
		result1 *node.Node
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDecoder) Decode(arg1 *registry.Node) (*node.Node, error) {
	fake.decodeMutex.Lock()
	ret, specificReturn := fake.decodeReturnsOnCall[len(fake.decodeArgsForCall)]
	fake.decodeArgsForCall = append(fake.decodeArgsForCall, struct {
		arg1 *registry.Node
	}{arg1})
	fake.recordInvocation("Decode", []interface{}{arg1})
	fake.decodeMutex.Unlock()
	if fake.DecodeStub != nil {
		return fake.DecodeStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.decodeReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDecoder) DecodeCallCount() int {
	fake.decodeMutex.RLock()
	defer fake.decodeMutex.RUnlock()
	return len(fake.decodeArgsForCall)
}

func (fake *FakeDecoder) DecodeCalls(stub func(*registry.Node) (*node.Node, error)) {
	fake.decodeMutex.Lock()
	defer fake.decodeMutex.Unlock()
	fake.DecodeStub = stub
}

func (fake *FakeDecoder) DecodeArgsForCall(i int) *registry.Node {
	fake.decodeMutex.RLock()
	defer fake.decodeMutex.RUnlock()
	argsForCall := fake.decodeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDecoder) DecodeReturns(result1 *node.Node, result2 error) {
	fake.decodeMutex.Lock()
	defer fake.decodeMutex.Unlock()
	fake.DecodeStub = nil
	fake.decodeReturns = struct {
		result1 *node.Node
		result2 error
	}{result1, result2}
}

func (fake *FakeDecoder) DecodeReturnsOnCall(i int, result1 *node.Node, result2 error) {
	fake.decodeMutex.Lock()
	defer fake.decodeMutex.Unlock()
	fake.DecodeStub = nil
	if fake.decodeReturnsOnCall == nil {
		fake.decodeReturnsOnCall = make(map[int]struct {
			result1 *node.Node
			result2 error
		})
	}
	fake.decodeReturnsOnCall[i] = struct {
		result1 *node.Node
		result2 error
	}{result1, result2}
}

func (fake *FakeDecoder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.decodeMutex.RLock()
	defer fake.decodeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDecoder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handlers.Decoder = new(FakeDecoder)
