# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/ankeesler/btool
    steps:
      - checkout
      - run: ./script/test.sh
      - setup_remote_docker
      - run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - run: ./script/build-container.sh btool
      - run: ./script/build-container.sh btoolregistry
      - run: ./script/push-container.sh btool
      - run: ./script/push-container.sh btoolregistry
      - run:
          name: Install CF CLI
          command: |
            # ...first add the Cloud Foundry Foundation public key and package repository to your system
            wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
            # ...then, update your local package index, then finally install the cf CLI
            sudo apt-get update
            sudo apt-get install cf-cli
            cf --version
      - run: cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io -o akeesler-org -s development
      - run: CF_DOCKER_PASSWORD=$DOCKER_PASSWORD ./script/cf-push.sh
