// Code generated by counterfeiter. DO NOT EDIT.
package registryfakes

import (
	"sync"

	"github.com/ankeesler/btool/collector"
	"github.com/ankeesler/btool/collector/registry"
	registrya "github.com/ankeesler/btool/registry"
)

type FakeGaggleCollector struct {
	CollectStub        func(*collector.Ctx, *registrya.Gaggle, string) error
	collectMutex       sync.RWMutex
	collectArgsForCall []struct {
		arg1 *collector.Ctx
		arg2 *registrya.Gaggle
		arg3 string
	}
	collectReturns struct {
		result1 error
	}
	collectReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGaggleCollector) Collect(arg1 *collector.Ctx, arg2 *registrya.Gaggle, arg3 string) error {
	fake.collectMutex.Lock()
	ret, specificReturn := fake.collectReturnsOnCall[len(fake.collectArgsForCall)]
	fake.collectArgsForCall = append(fake.collectArgsForCall, struct {
		arg1 *collector.Ctx
		arg2 *registrya.Gaggle
		arg3 string
	}{arg1, arg2, arg3})
	fake.recordInvocation("Collect", []interface{}{arg1, arg2, arg3})
	fake.collectMutex.Unlock()
	if fake.CollectStub != nil {
		return fake.CollectStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.collectReturns
	return fakeReturns.result1
}

func (fake *FakeGaggleCollector) CollectCallCount() int {
	fake.collectMutex.RLock()
	defer fake.collectMutex.RUnlock()
	return len(fake.collectArgsForCall)
}

func (fake *FakeGaggleCollector) CollectCalls(stub func(*collector.Ctx, *registrya.Gaggle, string) error) {
	fake.collectMutex.Lock()
	defer fake.collectMutex.Unlock()
	fake.CollectStub = stub
}

func (fake *FakeGaggleCollector) CollectArgsForCall(i int) (*collector.Ctx, *registrya.Gaggle, string) {
	fake.collectMutex.RLock()
	defer fake.collectMutex.RUnlock()
	argsForCall := fake.collectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeGaggleCollector) CollectReturns(result1 error) {
	fake.collectMutex.Lock()
	defer fake.collectMutex.Unlock()
	fake.CollectStub = nil
	fake.collectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGaggleCollector) CollectReturnsOnCall(i int, result1 error) {
	fake.collectMutex.Lock()
	defer fake.collectMutex.Unlock()
	fake.CollectStub = nil
	if fake.collectReturnsOnCall == nil {
		fake.collectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.collectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGaggleCollector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.collectMutex.RLock()
	defer fake.collectMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGaggleCollector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ registry.GaggleCollector = new(FakeGaggleCollector)
