// Code generated by counterfeiter. DO NOT EDIT.
package registryfakes

import (
	"sync"

	"github.com/ankeesler/btool/collector/registry"
	registrya "github.com/ankeesler/btool/registry"
)

type FakeGaggler struct {
	GaggleStub        func() (*registrya.Gaggle, error)
	gaggleMutex       sync.RWMutex
	gaggleArgsForCall []struct {
	}
	gaggleReturns struct {
		result1 *registrya.Gaggle
		result2 error
	}
	gaggleReturnsOnCall map[int]struct {
		result1 *registrya.Gaggle
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGaggler) Gaggle() (*registrya.Gaggle, error) {
	fake.gaggleMutex.Lock()
	ret, specificReturn := fake.gaggleReturnsOnCall[len(fake.gaggleArgsForCall)]
	fake.gaggleArgsForCall = append(fake.gaggleArgsForCall, struct {
	}{})
	fake.recordInvocation("Gaggle", []interface{}{})
	fake.gaggleMutex.Unlock()
	if fake.GaggleStub != nil {
		return fake.GaggleStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.gaggleReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGaggler) GaggleCallCount() int {
	fake.gaggleMutex.RLock()
	defer fake.gaggleMutex.RUnlock()
	return len(fake.gaggleArgsForCall)
}

func (fake *FakeGaggler) GaggleCalls(stub func() (*registrya.Gaggle, error)) {
	fake.gaggleMutex.Lock()
	defer fake.gaggleMutex.Unlock()
	fake.GaggleStub = stub
}

func (fake *FakeGaggler) GaggleReturns(result1 *registrya.Gaggle, result2 error) {
	fake.gaggleMutex.Lock()
	defer fake.gaggleMutex.Unlock()
	fake.GaggleStub = nil
	fake.gaggleReturns = struct {
		result1 *registrya.Gaggle
		result2 error
	}{result1, result2}
}

func (fake *FakeGaggler) GaggleReturnsOnCall(i int, result1 *registrya.Gaggle, result2 error) {
	fake.gaggleMutex.Lock()
	defer fake.gaggleMutex.Unlock()
	fake.GaggleStub = nil
	if fake.gaggleReturnsOnCall == nil {
		fake.gaggleReturnsOnCall = make(map[int]struct {
			result1 *registrya.Gaggle
			result2 error
		})
	}
	fake.gaggleReturnsOnCall[i] = struct {
		result1 *registrya.Gaggle
		result2 error
	}{result1, result2}
}

func (fake *FakeGaggler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.gaggleMutex.RLock()
	defer fake.gaggleMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGaggler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ registry.Gaggler = new(FakeGaggler)
