// Code generated by counterfeiter. DO NOT EDIT.
package builderfakes

import (
	"sync"

	"github.com/ankeesler/btool/builder"
)

type FakeToolchain struct {
	CompileCStub        func(string, string, []string) error
	compileCMutex       sync.RWMutex
	compileCArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 []string
	}
	compileCReturns struct {
		result1 error
	}
	compileCReturnsOnCall map[int]struct {
		result1 error
	}
	CompileCCStub        func(string, string, []string) error
	compileCCMutex       sync.RWMutex
	compileCCArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 []string
	}
	compileCCReturns struct {
		result1 error
	}
	compileCCReturnsOnCall map[int]struct {
		result1 error
	}
	LinkStub        func(string, []string) error
	linkMutex       sync.RWMutex
	linkArgsForCall []struct {
		arg1 string
		arg2 []string
	}
	linkReturns struct {
		result1 error
	}
	linkReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeToolchain) CompileC(arg1 string, arg2 string, arg3 []string) error {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.compileCMutex.Lock()
	ret, specificReturn := fake.compileCReturnsOnCall[len(fake.compileCArgsForCall)]
	fake.compileCArgsForCall = append(fake.compileCArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 []string
	}{arg1, arg2, arg3Copy})
	fake.recordInvocation("CompileC", []interface{}{arg1, arg2, arg3Copy})
	fake.compileCMutex.Unlock()
	if fake.CompileCStub != nil {
		return fake.CompileCStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.compileCReturns
	return fakeReturns.result1
}

func (fake *FakeToolchain) CompileCCallCount() int {
	fake.compileCMutex.RLock()
	defer fake.compileCMutex.RUnlock()
	return len(fake.compileCArgsForCall)
}

func (fake *FakeToolchain) CompileCCalls(stub func(string, string, []string) error) {
	fake.compileCMutex.Lock()
	defer fake.compileCMutex.Unlock()
	fake.CompileCStub = stub
}

func (fake *FakeToolchain) CompileCArgsForCall(i int) (string, string, []string) {
	fake.compileCMutex.RLock()
	defer fake.compileCMutex.RUnlock()
	argsForCall := fake.compileCArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeToolchain) CompileCReturns(result1 error) {
	fake.compileCMutex.Lock()
	defer fake.compileCMutex.Unlock()
	fake.CompileCStub = nil
	fake.compileCReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolchain) CompileCReturnsOnCall(i int, result1 error) {
	fake.compileCMutex.Lock()
	defer fake.compileCMutex.Unlock()
	fake.CompileCStub = nil
	if fake.compileCReturnsOnCall == nil {
		fake.compileCReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.compileCReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolchain) CompileCC(arg1 string, arg2 string, arg3 []string) error {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.compileCCMutex.Lock()
	ret, specificReturn := fake.compileCCReturnsOnCall[len(fake.compileCCArgsForCall)]
	fake.compileCCArgsForCall = append(fake.compileCCArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 []string
	}{arg1, arg2, arg3Copy})
	fake.recordInvocation("CompileCC", []interface{}{arg1, arg2, arg3Copy})
	fake.compileCCMutex.Unlock()
	if fake.CompileCCStub != nil {
		return fake.CompileCCStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.compileCCReturns
	return fakeReturns.result1
}

func (fake *FakeToolchain) CompileCCCallCount() int {
	fake.compileCCMutex.RLock()
	defer fake.compileCCMutex.RUnlock()
	return len(fake.compileCCArgsForCall)
}

func (fake *FakeToolchain) CompileCCCalls(stub func(string, string, []string) error) {
	fake.compileCCMutex.Lock()
	defer fake.compileCCMutex.Unlock()
	fake.CompileCCStub = stub
}

func (fake *FakeToolchain) CompileCCArgsForCall(i int) (string, string, []string) {
	fake.compileCCMutex.RLock()
	defer fake.compileCCMutex.RUnlock()
	argsForCall := fake.compileCCArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeToolchain) CompileCCReturns(result1 error) {
	fake.compileCCMutex.Lock()
	defer fake.compileCCMutex.Unlock()
	fake.CompileCCStub = nil
	fake.compileCCReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolchain) CompileCCReturnsOnCall(i int, result1 error) {
	fake.compileCCMutex.Lock()
	defer fake.compileCCMutex.Unlock()
	fake.CompileCCStub = nil
	if fake.compileCCReturnsOnCall == nil {
		fake.compileCCReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.compileCCReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolchain) Link(arg1 string, arg2 []string) error {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.linkMutex.Lock()
	ret, specificReturn := fake.linkReturnsOnCall[len(fake.linkArgsForCall)]
	fake.linkArgsForCall = append(fake.linkArgsForCall, struct {
		arg1 string
		arg2 []string
	}{arg1, arg2Copy})
	fake.recordInvocation("Link", []interface{}{arg1, arg2Copy})
	fake.linkMutex.Unlock()
	if fake.LinkStub != nil {
		return fake.LinkStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.linkReturns
	return fakeReturns.result1
}

func (fake *FakeToolchain) LinkCallCount() int {
	fake.linkMutex.RLock()
	defer fake.linkMutex.RUnlock()
	return len(fake.linkArgsForCall)
}

func (fake *FakeToolchain) LinkCalls(stub func(string, []string) error) {
	fake.linkMutex.Lock()
	defer fake.linkMutex.Unlock()
	fake.LinkStub = stub
}

func (fake *FakeToolchain) LinkArgsForCall(i int) (string, []string) {
	fake.linkMutex.RLock()
	defer fake.linkMutex.RUnlock()
	argsForCall := fake.linkArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeToolchain) LinkReturns(result1 error) {
	fake.linkMutex.Lock()
	defer fake.linkMutex.Unlock()
	fake.LinkStub = nil
	fake.linkReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolchain) LinkReturnsOnCall(i int, result1 error) {
	fake.linkMutex.Lock()
	defer fake.linkMutex.Unlock()
	fake.LinkStub = nil
	if fake.linkReturnsOnCall == nil {
		fake.linkReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.linkReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeToolchain) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.compileCMutex.RLock()
	defer fake.compileCMutex.RUnlock()
	fake.compileCCMutex.RLock()
	defer fake.compileCCMutex.RUnlock()
	fake.linkMutex.RLock()
	defer fake.linkMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeToolchain) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ builder.Toolchain = new(FakeToolchain)
