// Code generated by counterfeiter. DO NOT EDIT.
package pipelinefakes

import (
	"sync"

	"github.com/ankeesler/btool/node"
	"github.com/ankeesler/btool/node/pipeline"
)

type FakeCallback struct {
	OnAddStub        func(*node.Node)
	onAddMutex       sync.RWMutex
	onAddArgsForCall []struct {
		arg1 *node.Node
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCallback) OnAdd(arg1 *node.Node) {
	fake.onAddMutex.Lock()
	fake.onAddArgsForCall = append(fake.onAddArgsForCall, struct {
		arg1 *node.Node
	}{arg1})
	fake.recordInvocation("OnAdd", []interface{}{arg1})
	fake.onAddMutex.Unlock()
	if fake.OnAddStub != nil {
		fake.OnAddStub(arg1)
	}
}

func (fake *FakeCallback) OnAddCallCount() int {
	fake.onAddMutex.RLock()
	defer fake.onAddMutex.RUnlock()
	return len(fake.onAddArgsForCall)
}

func (fake *FakeCallback) OnAddCalls(stub func(*node.Node)) {
	fake.onAddMutex.Lock()
	defer fake.onAddMutex.Unlock()
	fake.OnAddStub = stub
}

func (fake *FakeCallback) OnAddArgsForCall(i int) *node.Node {
	fake.onAddMutex.RLock()
	defer fake.onAddMutex.RUnlock()
	argsForCall := fake.onAddArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCallback) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.onAddMutex.RLock()
	defer fake.onAddMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCallback) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pipeline.Callback = new(FakeCallback)
