// Code generated by counterfeiter. DO NOT EDIT.
package apifakes

import (
	"sync"

	"github.com/ankeesler/btool/node/registry"
	"github.com/ankeesler/btool/node/registry/api"
)

type FakeRegistry struct {
	IndexStub        func() (*registry.Index, error)
	indexMutex       sync.RWMutex
	indexArgsForCall []struct {
	}
	indexReturns struct {
		result1 *registry.Index
		result2 error
	}
	indexReturnsOnCall map[int]struct {
		result1 *registry.Index
		result2 error
	}
	NodesStub        func(string) ([]*registry.Node, error)
	nodesMutex       sync.RWMutex
	nodesArgsForCall []struct {
		arg1 string
	}
	nodesReturns struct {
		result1 []*registry.Node
		result2 error
	}
	nodesReturnsOnCall map[int]struct {
		result1 []*registry.Node
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRegistry) Index() (*registry.Index, error) {
	fake.indexMutex.Lock()
	ret, specificReturn := fake.indexReturnsOnCall[len(fake.indexArgsForCall)]
	fake.indexArgsForCall = append(fake.indexArgsForCall, struct {
	}{})
	fake.recordInvocation("Index", []interface{}{})
	fake.indexMutex.Unlock()
	if fake.IndexStub != nil {
		return fake.IndexStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.indexReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRegistry) IndexCallCount() int {
	fake.indexMutex.RLock()
	defer fake.indexMutex.RUnlock()
	return len(fake.indexArgsForCall)
}

func (fake *FakeRegistry) IndexCalls(stub func() (*registry.Index, error)) {
	fake.indexMutex.Lock()
	defer fake.indexMutex.Unlock()
	fake.IndexStub = stub
}

func (fake *FakeRegistry) IndexReturns(result1 *registry.Index, result2 error) {
	fake.indexMutex.Lock()
	defer fake.indexMutex.Unlock()
	fake.IndexStub = nil
	fake.indexReturns = struct {
		result1 *registry.Index
		result2 error
	}{result1, result2}
}

func (fake *FakeRegistry) IndexReturnsOnCall(i int, result1 *registry.Index, result2 error) {
	fake.indexMutex.Lock()
	defer fake.indexMutex.Unlock()
	fake.IndexStub = nil
	if fake.indexReturnsOnCall == nil {
		fake.indexReturnsOnCall = make(map[int]struct {
			result1 *registry.Index
			result2 error
		})
	}
	fake.indexReturnsOnCall[i] = struct {
		result1 *registry.Index
		result2 error
	}{result1, result2}
}

func (fake *FakeRegistry) Nodes(arg1 string) ([]*registry.Node, error) {
	fake.nodesMutex.Lock()
	ret, specificReturn := fake.nodesReturnsOnCall[len(fake.nodesArgsForCall)]
	fake.nodesArgsForCall = append(fake.nodesArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Nodes", []interface{}{arg1})
	fake.nodesMutex.Unlock()
	if fake.NodesStub != nil {
		return fake.NodesStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.nodesReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRegistry) NodesCallCount() int {
	fake.nodesMutex.RLock()
	defer fake.nodesMutex.RUnlock()
	return len(fake.nodesArgsForCall)
}

func (fake *FakeRegistry) NodesCalls(stub func(string) ([]*registry.Node, error)) {
	fake.nodesMutex.Lock()
	defer fake.nodesMutex.Unlock()
	fake.NodesStub = stub
}

func (fake *FakeRegistry) NodesArgsForCall(i int) string {
	fake.nodesMutex.RLock()
	defer fake.nodesMutex.RUnlock()
	argsForCall := fake.nodesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRegistry) NodesReturns(result1 []*registry.Node, result2 error) {
	fake.nodesMutex.Lock()
	defer fake.nodesMutex.Unlock()
	fake.NodesStub = nil
	fake.nodesReturns = struct {
		result1 []*registry.Node
		result2 error
	}{result1, result2}
}

func (fake *FakeRegistry) NodesReturnsOnCall(i int, result1 []*registry.Node, result2 error) {
	fake.nodesMutex.Lock()
	defer fake.nodesMutex.Unlock()
	fake.NodesStub = nil
	if fake.nodesReturnsOnCall == nil {
		fake.nodesReturnsOnCall = make(map[int]struct {
			result1 []*registry.Node
			result2 error
		})
	}
	fake.nodesReturnsOnCall[i] = struct {
		result1 []*registry.Node
		result2 error
	}{result1, result2}
}

func (fake *FakeRegistry) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.indexMutex.RLock()
	defer fake.indexMutex.RUnlock()
	fake.nodesMutex.RLock()
	defer fake.nodesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRegistry) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ api.Registry = new(FakeRegistry)
