// Code generated by counterfeiter. DO NOT EDIT.
package encodingfakes

import (
	"sync"

	"github.com/ankeesler/btool/node"
	"github.com/ankeesler/btool/node/encoding"
)

type FakeNodeMapper struct {
	MapStub        func(string) (*node.Node, error)
	mapMutex       sync.RWMutex
	mapArgsForCall []struct {
		arg1 string
	}
	mapReturns struct {
		result1 *node.Node
		result2 error
	}
	mapReturnsOnCall map[int]struct {
		result1 *node.Node
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNodeMapper) Map(arg1 string) (*node.Node, error) {
	fake.mapMutex.Lock()
	ret, specificReturn := fake.mapReturnsOnCall[len(fake.mapArgsForCall)]
	fake.mapArgsForCall = append(fake.mapArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Map", []interface{}{arg1})
	fake.mapMutex.Unlock()
	if fake.MapStub != nil {
		return fake.MapStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.mapReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNodeMapper) MapCallCount() int {
	fake.mapMutex.RLock()
	defer fake.mapMutex.RUnlock()
	return len(fake.mapArgsForCall)
}

func (fake *FakeNodeMapper) MapCalls(stub func(string) (*node.Node, error)) {
	fake.mapMutex.Lock()
	defer fake.mapMutex.Unlock()
	fake.MapStub = stub
}

func (fake *FakeNodeMapper) MapArgsForCall(i int) string {
	fake.mapMutex.RLock()
	defer fake.mapMutex.RUnlock()
	argsForCall := fake.mapArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeNodeMapper) MapReturns(result1 *node.Node, result2 error) {
	fake.mapMutex.Lock()
	defer fake.mapMutex.Unlock()
	fake.MapStub = nil
	fake.mapReturns = struct {
		result1 *node.Node
		result2 error
	}{result1, result2}
}

func (fake *FakeNodeMapper) MapReturnsOnCall(i int, result1 *node.Node, result2 error) {
	fake.mapMutex.Lock()
	defer fake.mapMutex.Unlock()
	fake.MapStub = nil
	if fake.mapReturnsOnCall == nil {
		fake.mapReturnsOnCall = make(map[int]struct {
			result1 *node.Node
			result2 error
		})
	}
	fake.mapReturnsOnCall[i] = struct {
		result1 *node.Node
		result2 error
	}{result1, result2}
}

func (fake *FakeNodeMapper) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mapMutex.RLock()
	defer fake.mapMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNodeMapper) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ encoding.NodeMapper = new(FakeNodeMapper)
