name: Main

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./script/lint.sh

  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./script/test.sh -u

  test-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./script/test.sh -i

  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./script/bench.sh

  build:
    needs: [lint, test-unit, test-integration, bench]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ankeesler/btool:latest

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./script/build-registry.sh -o build
    - uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: build

